import unittest
import _bootstrap  # noqa
from danzaboss.cortex.observation import (
    Observation, ObsType, Importance, ConfidenceSource)


class TestObservation(unittest.TestCase):
    def test_id_autogenerated_and_stable(self):
        o = Observation(title="Redis added", summary="s", type=ObsType.DECISION.value,
                        project="p", created="2026-07-01T00:00:00+00:00")
        self.assertTrue(o.id.startswith("obs_"))

    def test_confidence_source_mapping(self):
        self.assertEqual(Observation.confidence_for(ConfidenceSource.USER_STATED), 100)
        self.assertEqual(Observation.confidence_for(ConfidenceSource.SPECULATION), 20)

    def test_critical_never_expires(self):
        o = Observation(title="t", summary="s", type=ObsType.SECURITY.value,
                        project="p", importance=Importance.CRITICAL.value)
        self.assertIsNone(o.expires)

    def test_temporary_expires_soon(self):
        o = Observation(title="t", summary="s", type=ObsType.IMPL_DETAIL.value,
                        project="p", importance=Importance.TEMPORARY.value)
        self.assertIsNotNone(o.expires)

    def test_link_bag_lowercased_union(self):
        o = Observation(title="t", summary="s", type=ObsType.BUG_FIX.value, project="p",
                        concepts=["JWT"], files=["Auth.ts"], symbols=["refresh"])
        self.assertEqual(o.link_bag(), {"jwt", "auth.ts", "refresh"})


if __name__ == "__main__":
    unittest.main()
